name: Alert for Browser Smoke - Touchstone

on:
  workflow_dispatch:
    inputs:
        browser:
          required: true
          description: Browser Name
          
        version:
          required: true 
          description: Browser Version

        platform:
          required: true
          description: Platform

jobs:
  verify-inputs:
    name: Verify the provided Inputs
    runs-on: ubuntu
    defaults:
      run:
        shell: bash

    steps:
      - name: Show the Workflow trigger inputs
        run: |
          echo " ALL THE INPUTS PROVIDED IN WORKFLOW TRIGGER "
          echo Platform         : "${{ inputs.platform }}"
          echo Browser          : "${{ inputs.browser }}"
          echo Browser Version  : "${{ inputs.version }}"

  send_slack_message:
    runs-on: ubuntu
    environment: ${{github.ref_name}}-withoutapproval
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip3 install slack-sdk

      - name: Send Slack Message
        id: set_ts
        run: |
          ts_value=$(python tools/update-browser/browser_smoke_slack.py ":alert_blue: Running Smokes for Browser:${{inputs.browser}} | Version:${{inputs.version}} | Platform:${{inputs.platform}} :alert_blue:")
          echo "The 'ts' value is ----> $ts_value"
          echo "time_stamp=$ts_value" >> "$GITHUB_ENV"
          
      - name: Trigger Touchstone Browser Smoke
        run: |
          GITHUB_API_TOKEN="${{secrets.GIT_TOKEN}}"
          REPO_OWNER="LambdatestIncPrivate"
          REPO_NAME="hyperexecute-touchstone"
          WORKFLOW_NAME="browserselenium_version_validation.yml"
          BRANCH="master"

          SELENIUM_VERSION="4.0.0"
          echo "TIMESTAMP -> $time_stamp"
          
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_API_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/workflows/${WORKFLOW_NAME}/dispatches \
          -d "{\"ref\":\"${BRANCH}\", \"inputs\": {\"platform\":\"${{ inputs.platform }}\", \"browsers\":\"${{ inputs.browser }}\", \"versions\":\"${{ inputs.version }}\", \"selenium_versions\":\"$SELENIUM_VERSION\", \"time_stamp\":\"$time_stamp\"}}" \
          -vvv

          if [ $? -eq 0 ]; then
            echo "Workflow triggered successfully."
          else
            echo "Failed to trigger workflow."
          fi
