name: Cleanup Schedule for OS Images
on:
  # schedule:
  #   - cron: "25 12 * * 1" # Run every Monday at 12:25 PM
  workflow_dispatch:
jobs:
  cleanup:
    name: Cleanup the unused OS image versions
    runs-on: ubuntu
    environment: ${{github.ref_name}}-withoutapproval
    env:
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      GALLERY_NAME: ${{ vars.GALLERY_NAME }}
      GALLERY_IMAGE_DEFINITIONS: ${{ vars.GALLERY_IMAGE_DEFINITIONS }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run Python cleanup script
        working-directory: "azure-automation/cleanup"
        run: |
          ls -lah
          python --version
          python os-image-cleanup.py
